repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: check-merge-conflict
  - id: check-yaml
#  - id: detect-aws-credentials
  - id: detect-private-key
  - id: end-of-file-fixer
    exclude: ^\.idea/
#  - id: requirements-txt-fixer
  - id: trailing-whitespace
    exclude: ^\.idea/|.*\.md$
- repo: https://github.com/asottile/reorder_python_imports
  rev: v2.4.0
  hooks:
  - id: reorder-python-imports
- repo: https://github.com/ambv/black
  rev: 20.8b1
  hooks:
  - id: black
    language_version: python3.8
    args: [-l80]
    exclude: ^venv/
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.0
  hooks:
  - id: flake8
    exclude: ^(tests|venv)/
- repo: https://github.com/pre-commit/mirrors-fixmyjs
  rev: v2.0.0
  hooks:
  - id: fixmyjs
    args: ['-l', '-c', '.jshintrc']
- repo: https://github.com/pre-commit/mirrors-jshint
  rev: v2.12.0
  hooks:
  - id: jshint
