# Specifies the Python environment for this project. Create with `conda env create -f environment.yaml`.
name: gfc-financials
channels:
  - conda-forge   # required for functional camelot-py on Apple Silicon (arm64)
dependencies:
  - python=3.9
  - poetry=1.1.13
